// <auto-generated />
using ECom.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ECom.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ECom.Models.CartItems", b =>
                {
                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ECom.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Color = "White",
                            Description = "The Ferrari 488 (Type F142M) is a mid-engine sports car produced by the Italian automobile manufacturer Ferrari. The car is an update to the 458 with notable exterior and performance changes. The car is powered by a 3.9 - litre twin - turbocharged V8 engine, smaller in displacement but generating a higher power output than the 458's naturally aspirated engine. The 488 GTB was named 'The Supercar of the Year 2015' by car magazine Top Gear, as well as becoming Motor Trend's 2017 'Best Driver's Car'. ",
                            Image = "/assets/ferrari.jpg",
                            Name = "Ferrari 488 Spider",
                            Price = 280900.00m,
                            Sku = "TGYHBVCD",
                            Year = 2019
                        },
                        new
                        {
                            ID = 2,
                            Color = "Grey",
                            Description = "An icon cannot be reinvented, it can only be challenged. And only Aventador could surpass itself. This Lamborghini Aventador is a mid-engine sports car produced by the Italian automotive manufacturer Lamborghini. In keeping with Lamborghini tradition, the Aventador is named after a fighting bull.",
                            Image = "/assets/lambo.jpg",
                            Name = "Lamborghini Aventador S",
                            Price = 417826.00m,
                            Sku = "FLOMIJER",
                            Year = 2019
                        },
                        new
                        {
                            ID = 3,
                            Color = "White",
                            Description = "The Rolls-Royce Ghost is a British full-size luxury car manufactured by Rolls-Royce Motor Cars. The 'Ghost' nameplate, named in honour of the Silver Ghost, a car first produced in 1906, was announced in April 2009 at the Auto Shanghai show. During development, the Ghost was known as the 'RR04'.",
                            Image = "/assets/ghost.jpg",
                            Name = "Rolls-Royce Ghost",
                            Price = 351900.00m,
                            Sku = "PQASKFGV",
                            Year = 2019
                        },
                        new
                        {
                            ID = 4,
                            Color = "Grey",
                            Description = "The Porsche 911 is a two-door, 2+2 high performance rear-engined sports car made since in 1963 by Porsche AG of Stuttgart, Germany. It has a rear-mounted flat-six engine and all round independent suspension. It has undergone continuous development, though the basic concept has remained unchanged.",
                            Image = "/assets/911.jpg",
                            Name = "Porsche 911",
                            Price = 113300.00m,
                            Sku = "MVNCBRTY",
                            Year = 2019
                        },
                        new
                        {
                            ID = 5,
                            Color = "Black",
                            Description = "A handcrafted 621-hp biturbo V12 teams with a road-scanning, curve-tilting, fully active suspension in the AMG S 65. It's more than luxurious, and more than powerful. It's a sensation of majesty and magic no other sedan can match.",
                            Image = "/assets/benz.jpg",
                            Name = "Mercedes Benz S65",
                            Price = 230400.00m,
                            Sku = "LOFJKMDR",
                            Year = 2019
                        },
                        new
                        {
                            ID = 6,
                            Color = "White",
                            Description = "The BMW i8 is a plug-in hybrid sports car developed by BMW. The i8 is part of BMW's electric fleet 'Project i' being marketed as a new sub-brand, BMW i. The BMW i8 accelerates from 0 to 100 km / h(62 mph) in 4.4 seconds and has an electronic limited top speed of 250 km / h(155 mph).",
                            Image = "/assets/bmw.jpg",
                            Name = "BMW i8",
                            Price = 147500.00m,
                            Sku = "ASGTEFJN",
                            Year = 2019
                        },
                        new
                        {
                            ID = 7,
                            Color = "White",
                            Description = "The Tesla Roadster is an upcoming all-electric battery-powered four-seater sports car made by Tesla, Inc. Tesla has said it will be capable of 0 to 97 km/h (0 to 60 mph) in 1.9 seconds, quicker than any street legal production car to date at its announcement in November 2017. The Roadster is the successor to Tesla's first production car, which was the 2008 Roadster.",
                            Image = "/assets/tesla.jpg",
                            Name = "Tesla Roadster",
                            Price = 200000.00m,
                            Sku = "QSDEWFTG",
                            Year = 2020
                        },
                        new
                        {
                            ID = 8,
                            Color = "Grey",
                            Description = "The Jaguar F-type is a quintessential sports car, with a head-turning design and high-octane performance. This Jaguar two-seater takes form as either a sleek coupe or a stunning convertible. Along with a snarling supercharged V-6, the 2020 F-type offers a more affordable turbocharged four-cylinder engine.",
                            Image = "/assets/jag.jpg",
                            Name = "Jaguar F-TYPE",
                            Price = 61600.00m,
                            Sku = "POLEDFRT",
                            Year = 2019
                        },
                        new
                        {
                            ID = 9,
                            Color = "Light Grey",
                            Description = "The Audi R8 is a mid-engine, 2-seater sports car, which uses Audi's trademark quattro permanent all-wheel drive system. It was introduced by the German car manufacturer Audi AG in 2006. The car is exclusively designed, developed, and manufactured by Audi AG's private subsidiary company manufacturing high performance automotive parts, Audi Sport GmbH (formerly quattro GmbH), and is based on the Lamborghini Gallardo and presently the Huracán platform.",
                            Image = "/assets/audi.jpg",
                            Name = "Audi R8",
                            Price = 169900.00m,
                            Sku = "JGNMHKTE",
                            Year = 2019
                        },
                        new
                        {
                            ID = 10,
                            Color = "Black",
                            Description = "The Bentley Bentayga is a mid-size, front-engine, all-wheel drive, five-door luxury crossover marketed by Bentley, beginning with model year 2016. Its body is manufactured at the Volkswagen Zwickau-Mosel plant, then painted by Paintbox Editions in Banbury, and finally assembled at the company's Crewe factory.",
                            Image = "/assets/bentley.jpg",
                            Name = "Bentley Bentayga",
                            Price = 165000.00m,
                            Sku = "BGHVDPWO",
                            Year = 2019
                        });
                });

            modelBuilder.Entity("ECom.Models.cart", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CartID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("ECom.Models.CartItems", b =>
                {
                    b.HasOne("ECom.Models.cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECom.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
